import SectionNavButtons from '../components/SectionNavButtons';

export default function AerodynamicsPage() {
  return (
    <div>
      <header className="mb-12">
        <h2 className="text-sm font-black text-gray-400 uppercase tracking-wider">The Car</h2>
        <h1 className="mt-1 text-5xl uppercase font-black text-transparent bg-gradient-to-r from-[#FFD37B] to-[#FFC857] bg-clip-text">
          Aerodynamics
        </h1>
      </header>

      <section className="mb-8">
        <p className="text-gray-300 text-lg">
          Aerodynamics is the science of how air flows around the car. In F1, it's crucial for generating downforce and managing drag to maximize speed and cornering performance.
        </p>
      </section>

      {/* Downforce */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">Downforce</h2>
        <p className="text-gray-300 mb-4">
          Downforce is the vertical force pushing the car down onto the track, generated by airflow over and under the car. More downforce means more grip and faster cornering.
        </p>
        <div className="bg-gray-900/50 p-4 rounded">
          <p className="text-sm font-semibold text-gray-200 mb-2">Benefits:</p>
          <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
            <li>Higher cornering speeds</li>
            <li>Better braking performance</li>
            <li>Improved stability at high speed</li>
            <li>More mechanical grip on the tires</li>
          </ul>
        </div>
        <div className="bg-red-900/30 border border-red-600 rounded p-4 mt-3">
          <p className="text-sm font-semibold text-red-400 mb-2">Trade-off:</p>
          <p className="text-sm text-gray-300">More downforce creates more drag, reducing straight-line speed. Teams must balance downforce and drag for each circuit.</p>
        </div>
      </section>

      {/* Front Wing */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">Front Wing</h2>
        <p className="text-gray-300 mb-4">
          The most forward aerodynamic element, responsible for about 25-30% of the car's total downforce and directing airflow to the rest of the car.
        </p>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold text-gray-100 mb-2">Functions:</h3>
            <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
              <li>Generates front-end downforce for steering</li>
              <li>Directs air around the front tires</li>
              <li>Conditions airflow for rear aerodynamics</li>
              <li>Can be adjusted between sessions</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Rear Wing */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">Rear Wing</h2>
        <p className="text-gray-300 mb-4">
          The large wing at the back of the car generates significant downforce on the rear tires and houses the DRS system.
        </p>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold text-gray-100 mb-2">Configuration Types:</h3>
            <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
              <li><span className="font-semibold">High downforce</span>: Steeper angle, for twisty circuits (Monaco, Hungary)</li>
              <li><span className="font-semibold">Low downforce</span>: Flatter angle, for high-speed circuits (Monza, Spa)</li>
              <li><span className="font-semibold">Medium downforce</span>: Balanced setup for most tracks</li>
            </ul>
          </div>
        </div>
      </section>

      {/* DRS */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">DRS (Drag Reduction System)</h2>
        <p className="text-gray-300 mb-4">
          A movable flap in the rear wing that opens to reduce drag and increase straight-line speed, aiding overtaking.
        </p>
        <div className="bg-gray-900/50 p-4 rounded mb-3">
          <p className="text-sm font-semibold text-gray-200 mb-2">Rules:</p>
          <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
            <li>Available in designated DRS zones</li>
            <li>Driver must be within 1 second of car ahead</li>
            <li>Not available on first two laps after start/restart</li>
            <li>Disabled in wet conditions</li>
          </ul>
        </div>
        <div className="bg-green-900/30 border border-green-600 rounded p-4">
          <p className="text-sm font-semibold text-green-400 mb-2">Effect:</p>
          <p className="text-sm text-gray-300">Opens rear wing flap by 85mm, reducing drag by approximately 10-15% and increasing top speed by 10-20 km/h</p>
        </div>
      </section>

      {/* Floor and Diffuser */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">Floor & Diffuser</h2>
        <p className="text-gray-300 mb-4">
          The underside of the car is the largest aerodynamic surface, generating massive amounts of downforce through ground effect.
        </p>
        <div className="space-y-3">
          <div>
            <h3 className="font-semibold text-gray-100 mb-2">How it Works:</h3>
            <p className="text-sm text-gray-300 mb-2">
              Air is accelerated under the car through Venturi tunnels, creating low pressure that sucks the car to the ground.
            </p>
          </div>
          <div className="bg-gray-900/50 p-4 rounded">
            <p className="text-sm font-semibold text-gray-200 mb-2">Key Components:</p>
            <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
              <li><span className="font-semibold">Diffuser</span>: Expands airflow at the rear to increase suction</li>
              <li><span className="font-semibold">Edge wings</span>: Guide airflow and seal the floor</li>
              <li><span className="font-semibold">Plank</span>: Wooden strip that ensures minimum ride height</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Dirty Air */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">Dirty Air & Slipstream</h2>
        <div className="space-y-4">
          <div>
            <h3 className="font-semibold text-gray-100 mb-2">Dirty Air</h3>
            <p className="text-sm text-gray-300 mb-2">
              Turbulent air left behind by a car ahead disrupts the following car's aerodynamics, reducing downforce and making overtaking difficult.
            </p>
            <div className="bg-red-900/30 border border-red-600 rounded p-3 text-sm text-gray-300">
              Following closely can cause a loss of 30-40% downforce, making the car unstable and causing tire overheating.
            </div>
          </div>
          <div>
            <h3 className="font-semibold text-gray-100 mb-2">Slipstream</h3>
            <p className="text-sm text-gray-300 mb-2">
              The reduced air resistance in the wake of another car, allowing the following car to go faster on straights.
            </p>
            <div className="bg-green-900/30 border border-green-600 rounded p-3 text-sm text-gray-300">
              Can provide 5-15 km/h speed advantage, crucial for overtaking on straights.
            </div>
          </div>
        </div>
      </section>

      {/* Cooling */}
      <section className="mb-8 bg-white/5 rounded-lg p-6 border border-white/10">
        <h2 className="text-2xl font-bold text-gray-100 mb-4">Cooling vs. Aerodynamics</h2>
        <p className="text-gray-300 mb-4">
          Teams must balance aerodynamic efficiency with engine and brake cooling requirements.
        </p>
        <div className="bg-gray-900/50 p-4 rounded">
          <p className="text-sm font-semibold text-gray-200 mb-2">The Challenge:</p>
          <ul className="list-disc list-inside space-y-1 text-sm text-gray-300">
            <li>Larger cooling vents = more drag but better cooling</li>
            <li>Smaller vents = less drag but risk of overheating</li>
            <li>Hot weather requires bigger openings</li>
            <li>Each circuit needs different cooling configuration</li>
          </ul>
        </div>
      </section>

      <SectionNavButtons />
    </div>
  );
}
